### ISSUE TITLE
Changed LS_cid does not run for IgTrading

### ISSUE THREAD

**Issue by teebeast** [Lightstreamer/Lightstreamer-lib-client-dotnet#1]
I cloned this project and the latest changes and it raised the following exception:

> CONERR,60,License not valid for this Client version

In your last changeset you changed the LS_cid. When resetting it to the old value, I can connect to the server.

``` csharp
this.addParameter("LS_cid", "jqWtj1twChtfDxikwp1ltvc64CJ4Ji kOj2Cr");        // Old
this.addParameter("LS_cid", "jqWtj1twChtfDxikwp1ltvcB4CJ5Kj uWur8vy1sj.gk"); // New
```

I don't know for what this is good for, but it can't be parameterized. Maybe this should be configurable on `LightstreamerClient`s connection details. Can you give me some insides to this change?

Thanks

**Comment by Bravo27** [comment]
The change implements a new policy for the public clients identification. I also confirm that is intended to be embedded in the code and not configurable by the API.
This latest change probably no longer meets [IG API usage policies](https://labs.ig.com/lightstreamer-downloads).

You could just revert the last change and test the lib anyway or maybe go back to a 5.0 tag.
