### ISSUE TITLE
call a bunch of  bind_session when network error

### ISSUE THREAD

**Issue by phandienthinh** [Lightstreamer/Lightstreamer-lib-client-dotnet#2]
After app got disconnect/issue connect, client will call bind_session loop many times without delay.

Then I digging code and saw that function _**bindSent**_  used **Unix Expoch Time** but function **_calculateRetryDelay_** use **DateTime.Now** for calculated.
I have add a attachment file for fixed this issues - all time will use Unix Expoct Time 
[Session.txt](https://github.com/Lightstreamer/Lightstreamer-lib-client-dotnet/files/8728504/Session.txt)

**Comment by Bravo27** [comment]
Thanks for reporting the issue, I can confirm that we will update the code with something similar to your changes.

**Comment by Bravo27** [comment]
Fixed with commit [7728c9b](https://github.com/Lightstreamer/Lightstreamer-lib-client-dotnet/commit/7728c9bf2bfa6a2fe128ea392e07a239c4e06aae)
